services:
  app:
    build: .
    container_name: app
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - default
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.app.rule=Host(`app.up-csi.org`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.services.app.loadbalancer.server.port=3000"
      - "traefik.http.routers.app.tls=true"

networks:
  traefik_net:
    external: true
